// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, The OpenROAD Authors

#pragma once

#include <cstddef>
#include <vector>

namespace fin {

// Input generated by J40's multilevel density analysis.  Tiles may have
// different sizes, but must form the disjoint tile set used by every window.
struct MLFixedDissectionLpProblem
{
  double max_density;
  std::vector<double> tile_areas;
  std::vector<double> feature_areas;
  std::vector<double> max_fill_areas;
  // Indices of tiles contributing to each window examined during analysis.
  std::vector<std::vector<size_t>> windows;
};

struct MLFixedDissectionLpResult
{
  bool solved = false;
  double min_window_area = 0.0;
  std::vector<double> fill_areas;
};

// Solve J40's multilevel fill-amount LP.  The variables are the fill amounts
// of tiles retained by multilevel density analysis, and constraints are added
// only for windows examined during that analysis.
// Throws std::invalid_argument when the problem dimensions are inconsistent.
MLFixedDissectionLpResult solveMLFixedDissectionLp(
    const MLFixedDissectionLpProblem& problem);

}  // namespace fin
